import { LocationItem, CameraFeed, SmartAlert, ThresholdSettings } from './types';

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'canteen',
    name: 'Canteen',
    category: 'Dining',
    status: 'Medium',
    peopleCount: 48,
    maxCapacity: 80,
    estimatedWaitMin: 8,
    queueDensityPercent: 60,
    avgServiceTimeSec: 15,
    lastUpdated: 'Just now',
    cameraCode: 'CAM-01',
    recommendedTimeWindow: '2:30 PM – 3:30 PM',
    queueGrowthPercent: 6,
    serviceRatePeoplePerMin: 4.0,
    mapX: 25,
    mapY: 35,
    description: 'Main campus food court and central dining hall serving lunch, snacks, and beverages.',
    hourlyTrends: [
      { time: '08:00 AM', count: 14, wait: 3 },
      { time: '10:00 AM', count: 28, wait: 5 },
      { time: '12:00 PM', count: 68, wait: 14 },
      { time: '01:30 PM', count: 48, wait: 8 },
      { time: '03:00 PM', count: 22, wait: 4 },
      { time: '05:00 PM', count: 36, wait: 6 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 10, peakPeople: 72 },
      { day: 'Tue', avgWait: 8, peakPeople: 65 },
      { day: 'Wed', avgWait: 12, peakPeople: 78 },
      { day: 'Thu', avgWait: 7, peakPeople: 58 },
      { day: 'Fri', avgWait: 14, peakPeople: 82 },
    ],
  },
  {
    id: 'admin-office',
    name: 'Administrative Office',
    category: 'Admin',
    status: 'High',
    peopleCount: 72,
    maxCapacity: 75,
    estimatedWaitMin: 27,
    queueDensityPercent: 96,
    avgServiceTimeSec: 45,
    lastUpdated: '5 sec ago',
    cameraCode: 'CAM-03',
    recommendedTimeWindow: '8:30 AM – 9:30 AM',
    queueGrowthPercent: 14,
    serviceRatePeoplePerMin: 1.5,
    mapX: 68,
    mapY: 28,
    description: 'Official student transcript issuance, bonafide verification, and general university admin clearance.',
    hourlyTrends: [
      { time: '08:00 AM', count: 18, wait: 6 },
      { time: '10:00 AM', count: 52, wait: 18 },
      { time: '12:00 PM', count: 78, wait: 29 },
      { time: '01:30 PM', count: 72, wait: 27 },
      { time: '03:00 PM', count: 56, wait: 20 },
      { time: '05:00 PM', count: 24, wait: 8 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 28, peakPeople: 85 },
      { day: 'Tue', avgWait: 22, peakPeople: 74 },
      { day: 'Wed', avgWait: 25, peakPeople: 79 },
      { day: 'Thu', avgWait: 20, peakPeople: 71 },
      { day: 'Fri', avgWait: 31, peakPeople: 90 },
    ],
  },
  {
    id: 'library',
    name: 'Central Library',
    category: 'Academic',
    status: 'Low',
    peopleCount: 14,
    maxCapacity: 60,
    estimatedWaitMin: 3,
    queueDensityPercent: 23,
    avgServiceTimeSec: 12,
    lastUpdated: '12 sec ago',
    cameraCode: 'CAM-02',
    recommendedTimeWindow: '10:00 AM – 11:30 AM',
    queueGrowthPercent: -10,
    serviceRatePeoplePerMin: 5.0,
    mapX: 45,
    mapY: 60,
    description: 'Book issue/return counter, study room reservation desk, and digital archives access.',
    hourlyTrends: [
      { time: '08:00 AM', count: 6, wait: 1 },
      { time: '10:00 AM', count: 18, wait: 4 },
      { time: '12:00 PM', count: 32, wait: 7 },
      { time: '01:30 PM', count: 14, wait: 3 },
      { time: '03:00 PM', count: 20, wait: 4 },
      { time: '05:00 PM', count: 9, wait: 2 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 4, peakPeople: 35 },
      { day: 'Tue', avgWait: 3, peakPeople: 30 },
      { day: 'Wed', avgWait: 5, peakPeople: 40 },
      { day: 'Thu', avgWait: 3, peakPeople: 28 },
      { day: 'Fri', avgWait: 6, peakPeople: 44 },
    ],
  },
  {
    id: 'student-services',
    name: 'Student Services',
    category: 'Services',
    status: 'Medium',
    peopleCount: 38,
    maxCapacity: 50,
    estimatedWaitMin: 14,
    queueDensityPercent: 76,
    avgServiceTimeSec: 22,
    lastUpdated: '8 sec ago',
    cameraCode: 'CAM-04',
    recommendedTimeWindow: '3:45 PM – 4:30 PM',
    queueGrowthPercent: 4,
    serviceRatePeoplePerMin: 2.7,
    mapX: 75,
    mapY: 70,
    description: 'ID card renewal, campus housing support, counseling appointment check-in, and lost & found.',
    hourlyTrends: [
      { time: '08:00 AM', count: 12, wait: 4 },
      { time: '10:00 AM', count: 30, wait: 10 },
      { time: '12:00 PM', count: 46, wait: 17 },
      { time: '01:30 PM', count: 38, wait: 14 },
      { time: '03:00 PM', count: 26, wait: 9 },
      { time: '05:00 PM', count: 15, wait: 5 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 15, peakPeople: 52 },
      { day: 'Tue', avgWait: 12, peakPeople: 45 },
      { day: 'Wed', avgWait: 14, peakPeople: 49 },
      { day: 'Thu', avgWait: 11, peakPeople: 42 },
      { day: 'Fri', avgWait: 17, peakPeople: 56 },
    ],
  },
  {
    id: 'fee-counter',
    name: 'Fee Counter',
    category: 'Finance',
    status: 'High',
    peopleCount: 55,
    maxCapacity: 65,
    estimatedWaitMin: 18,
    queueDensityPercent: 85,
    avgServiceTimeSec: 30,
    lastUpdated: '15 sec ago',
    cameraCode: 'CAM-06',
    recommendedTimeWindow: '8:00 AM – 9:00 AM',
    queueGrowthPercent: 18,
    serviceRatePeoplePerMin: 2.0,
    mapX: 30,
    mapY: 75,
    description: 'Tuition payment clearance, scholarship disbursement verification, and penalty desk.',
    hourlyTrends: [
      { time: '08:00 AM', count: 16, wait: 5 },
      { time: '10:00 AM', count: 42, wait: 14 },
      { time: '12:00 PM', count: 62, wait: 21 },
      { time: '01:30 PM', count: 55, wait: 18 },
      { time: '03:00 PM', count: 38, wait: 12 },
      { time: '05:00 PM', count: 19, wait: 6 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 20, peakPeople: 68 },
      { day: 'Tue', avgWait: 16, peakPeople: 58 },
      { day: 'Wed', avgWait: 15, peakPeople: 55 },
      { day: 'Thu', avgWait: 14, peakPeople: 52 },
      { day: 'Fri', avgWait: 22, peakPeople: 72 },
    ],
  },
  {
    id: 'transport-office',
    name: 'Transport Office',
    category: 'Transit',
    status: 'Low',
    peopleCount: 9,
    maxCapacity: 40,
    estimatedWaitMin: 2,
    queueDensityPercent: 22,
    avgServiceTimeSec: 10,
    lastUpdated: '20 sec ago',
    cameraCode: 'CAM-05',
    recommendedTimeWindow: '11:00 AM – 12:00 PM',
    queueGrowthPercent: -15,
    serviceRatePeoplePerMin: 6.0,
    mapX: 15,
    mapY: 55,
    description: 'Shuttle bus pass issuance, parking permit allocation, and campus transit schedule desk.',
    hourlyTrends: [
      { time: '08:00 AM', count: 22, wait: 5 },
      { time: '10:00 AM', count: 14, wait: 3 },
      { time: '12:00 PM', count: 16, wait: 4 },
      { time: '01:30 PM', count: 9, wait: 2 },
      { time: '03:00 PM', count: 12, wait: 3 },
      { time: '05:00 PM', count: 25, wait: 6 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 5, peakPeople: 30 },
      { day: 'Tue', avgWait: 3, peakPeople: 24 },
      { day: 'Wed', avgWait: 3, peakPeople: 22 },
      { day: 'Thu', avgWait: 2, peakPeople: 20 },
      { day: 'Fri', avgWait: 6, peakPeople: 33 },
    ],
  },
];

export const INITIAL_CAMERAS: CameraFeed[] = [
  {
    id: 'cam-01',
    code: 'CAM-01',
    locationId: 'canteen',
    locationName: 'Canteen Entrance',
    status: 'LIVE',
    fps: 4.8,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 48,
    modelConfidence: 0.94,
    processingLatencyMs: 42,
  },
  {
    id: 'cam-02',
    code: 'CAM-02',
    locationId: 'library',
    locationName: 'Library Helpdesk',
    status: 'LIVE',
    fps: 5.0,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 14,
    modelConfidence: 0.96,
    processingLatencyMs: 38,
  },
  {
    id: 'cam-03',
    code: 'CAM-03',
    locationId: 'admin-office',
    locationName: 'Admin Clearance Desk',
    status: 'LIVE',
    fps: 4.2,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 72,
    modelConfidence: 0.91,
    processingLatencyMs: 55,
  },
  {
    id: 'cam-04',
    code: 'CAM-04',
    locationId: 'student-services',
    locationName: 'Student Services Foyer',
    status: 'UNSTABLE',
    fps: 2.1,
    queueRegionActive: true,
    resolution: '1280x720 @ 15fps',
    detectedPeopleCount: 38,
    modelConfidence: 0.88,
    processingLatencyMs: 110,
  },
  {
    id: 'cam-05',
    code: 'CAM-05',
    locationId: 'transport-office',
    locationName: 'Transport Permit Window',
    status: 'LIVE',
    fps: 5.0,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 9,
    modelConfidence: 0.95,
    processingLatencyMs: 34,
  },
  {
    id: 'cam-06',
    code: 'CAM-06',
    locationId: 'fee-counter',
    locationName: 'Fee Disbursement Hall',
    status: 'LIVE',
    fps: 4.6,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 55,
    modelConfidence: 0.93,
    processingLatencyMs: 40,
  },
];

export const INITIAL_ALERTS: SmartAlert[] = [
  {
    id: 'alert-1',
    severity: 'critical',
    type: 'CONGESTION',
    locationId: 'admin-office',
    locationName: 'Administrative Office',
    timestamp: '2 min ago',
    title: 'HIGH CONGESTION SURGE',
    description: 'Administrative Office queue reached 72 people (96% density). Estimated wait time is 27 min.',
    isRead: false,
  },
  {
    id: 'alert-2',
    severity: 'critical',
    type: 'CONGESTION',
    locationId: 'fee-counter',
    locationName: 'Fee Counter',
    timestamp: '5 min ago',
    title: 'FEE COUNTER SURGE',
    description: 'Fee Counter inflow increased +18%. 55 people waiting with an estimated wait time of 18 min.',
    isRead: false,
  },
  {
    id: 'alert-3',
    severity: 'warning',
    type: 'WAIT_TIME',
    locationId: 'student-services',
    locationName: 'Student Services',
    timestamp: '11 min ago',
    title: 'WAIT TIME ESCALATION',
    description: 'Student Services wait time increased to 14 minutes due to ID card renewal rush.',
    isRead: false,
  },
  {
    id: 'alert-4',
    severity: 'success',
    type: 'IMPROVEMENT',
    locationId: 'library',
    locationName: 'Central Library',
    timestamp: '16 min ago',
    title: 'OPTIMAL QUEUE FLOW',
    description: 'Library queue decreased by 10%. Currently only 14 people with a 3 min expected wait time.',
    isRead: true,
  },
  {
    id: 'alert-5',
    severity: 'warning',
    type: 'CAMERA_STATUS',
    locationId: 'student-services',
    locationName: 'Student Services',
    timestamp: '25 min ago',
    title: 'CAMERA FPS DROP',
    description: 'Camera CAM-04 connection frame rate dropped to 2.1 FPS. Sampling latency increased to 110ms.',
    isRead: true,
  },
];

export const DEFAULT_THRESHOLDS: ThresholdSettings = {
  lowMax: 30,
  mediumMax: 60,
  highMin: 61,
  alertSensitivity: 'medium',
  autoStaffNotification: true,
  emailAlertsEnabled: false,
};
