import { LocationItem, CameraFeed, SmartAlert, ThresholdSettings } from './types';

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'canteen',
    name: 'Canteen',
    category: 'Dining',
    status: 'Medium',
    peopleCount: 42,
    maxCapacity: 65,
    estimatedWaitMin: 12,
    queueDensityPercent: 65,
    avgServiceTimeSec: 17,
    lastUpdated: 'Just now',
    cameraCode: 'CAM-01',
    recommendedTimeWindow: '3:30 PM – 4:00 PM',
    queueGrowthPercent: 8,
    serviceRatePeoplePerMin: 3.5,
    mapX: 25,
    mapY: 35,
    description: 'Main campus food court and central dining hall serving lunch, snacks, and beverages.',
    hourlyTrends: [
      { time: '08:00 AM', count: 12, wait: 3 },
      { time: '10:00 AM', count: 24, wait: 7 },
      { time: '12:00 PM', count: 58, wait: 18 },
      { time: '01:30 PM', count: 42, wait: 12 },
      { time: '03:00 PM', count: 18, wait: 5 },
      { time: '05:00 PM', count: 31, wait: 9 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 14, peakPeople: 62 },
      { day: 'Tue', avgWait: 12, peakPeople: 55 },
      { day: 'Wed', avgWait: 15, peakPeople: 64 },
      { day: 'Thu', avgWait: 11, peakPeople: 51 },
      { day: 'Fri', avgWait: 16, peakPeople: 68 },
    ],
  },
  {
    id: 'admin-office',
    name: 'Administrative Office',
    category: 'Admin',
    status: 'High',
    peopleCount: 67,
    maxCapacity: 75,
    estimatedWaitMin: 21,
    queueDensityPercent: 89,
    avgServiceTimeSec: 45,
    lastUpdated: '10 sec ago',
    cameraCode: 'CAM-03',
    recommendedTimeWindow: '9:00 AM – 10:00 AM',
    queueGrowthPercent: 14,
    serviceRatePeoplePerMin: 1.8,
    mapX: 68,
    mapY: 28,
    description: 'Official student transcript issuance, bonafide verification, and general university admin clearance.',
    hourlyTrends: [
      { time: '08:00 AM', count: 15, wait: 5 },
      { time: '10:00 AM', count: 48, wait: 15 },
      { time: '12:00 PM', count: 72, wait: 24 },
      { time: '01:30 PM', count: 67, wait: 21 },
      { time: '03:00 PM', count: 52, wait: 16 },
      { time: '05:00 PM', count: 20, wait: 6 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 22, peakPeople: 75 },
      { day: 'Tue', avgWait: 19, peakPeople: 68 },
      { day: 'Wed', avgWait: 20, peakPeople: 70 },
      { day: 'Thu', avgWait: 18, peakPeople: 65 },
      { day: 'Fri', avgWait: 25, peakPeople: 82 },
    ],
  },
  {
    id: 'library',
    name: 'Central Library',
    category: 'Academic',
    status: 'Low',
    peopleCount: 18,
    maxCapacity: 50,
    estimatedWaitMin: 4,
    queueDensityPercent: 36,
    avgServiceTimeSec: 12,
    lastUpdated: '15 sec ago',
    cameraCode: 'CAM-02',
    recommendedTimeWindow: 'Current time is optimal',
    queueGrowthPercent: -22,
    serviceRatePeoplePerMin: 4.8,
    mapX: 45,
    mapY: 60,
    description: 'Book issue/return counter, study room reservation desk, and digital archives access.',
    hourlyTrends: [
      { time: '08:00 AM', count: 8, wait: 2 },
      { time: '10:00 AM', count: 22, wait: 5 },
      { time: '12:00 PM', count: 35, wait: 8 },
      { time: '01:30 PM', count: 18, wait: 4 },
      { time: '03:00 PM', count: 25, wait: 6 },
      { time: '05:00 PM', count: 10, wait: 2 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 5, peakPeople: 38 },
      { day: 'Tue', avgWait: 4, peakPeople: 32 },
      { day: 'Wed', avgWait: 6, peakPeople: 42 },
      { day: 'Thu', avgWait: 5, peakPeople: 35 },
      { day: 'Fri', avgWait: 7, peakPeople: 46 },
    ],
  },
  {
    id: 'student-services',
    name: 'Student Services',
    category: 'Services',
    status: 'Medium',
    peopleCount: 34,
    maxCapacity: 55,
    estimatedWaitMin: 10,
    queueDensityPercent: 61,
    avgServiceTimeSec: 25,
    lastUpdated: '5 sec ago',
    cameraCode: 'CAM-04',
    recommendedTimeWindow: '2:00 PM – 3:00 PM',
    queueGrowthPercent: 3,
    serviceRatePeoplePerMin: 2.8,
    mapX: 75,
    mapY: 70,
    description: 'ID card renewal, campus housing support, counseling appointment check-in, and lost & found.',
    hourlyTrends: [
      { time: '08:00 AM', count: 10, wait: 3 },
      { time: '10:00 AM', count: 28, wait: 8 },
      { time: '12:00 PM', count: 40, wait: 12 },
      { time: '01:30 PM', count: 34, wait: 10 },
      { time: '03:00 PM', count: 22, wait: 6 },
      { time: '05:00 PM', count: 12, wait: 3 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 11, peakPeople: 48 },
      { day: 'Tue', avgWait: 9, peakPeople: 41 },
      { day: 'Wed', avgWait: 10, peakPeople: 44 },
      { day: 'Thu', avgWait: 8, peakPeople: 38 },
      { day: 'Fri', avgWait: 13, peakPeople: 52 },
    ],
  },
  {
    id: 'fee-counter',
    name: 'Fee Counter',
    category: 'Finance',
    status: 'Low',
    peopleCount: 14,
    maxCapacity: 45,
    estimatedWaitMin: 3,
    queueDensityPercent: 31,
    avgServiceTimeSec: 20,
    lastUpdated: '1 min ago',
    cameraCode: 'CAM-06',
    recommendedTimeWindow: 'Current time is optimal',
    queueGrowthPercent: -5,
    serviceRatePeoplePerMin: 4.2,
    mapX: 30,
    mapY: 75,
    description: 'Tuition payment clearance, scholarship disbursement verification, and penalty desk.',
    hourlyTrends: [
      { time: '08:00 AM', count: 5, wait: 1 },
      { time: '10:00 AM', count: 38, wait: 10 },
      { time: '12:00 PM', count: 45, wait: 14 },
      { time: '01:30 PM', count: 14, wait: 3 },
      { time: '03:00 PM', count: 20, wait: 5 },
      { time: '05:00 PM', count: 8, wait: 2 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 15, peakPeople: 55 },
      { day: 'Tue', avgWait: 8, peakPeople: 40 },
      { day: 'Wed', avgWait: 6, peakPeople: 32 },
      { day: 'Thu', avgWait: 5, peakPeople: 28 },
      { day: 'Fri', avgWait: 12, peakPeople: 48 },
    ],
  },
  {
    id: 'transport-office',
    name: 'Transport Office',
    category: 'Transit',
    status: 'Low',
    peopleCount: 12,
    maxCapacity: 40,
    estimatedWaitMin: 3,
    queueDensityPercent: 30,
    avgServiceTimeSec: 15,
    lastUpdated: '30 sec ago',
    cameraCode: 'CAM-05',
    recommendedTimeWindow: 'Current time is optimal',
    queueGrowthPercent: 0,
    serviceRatePeoplePerMin: 4.5,
    mapX: 15,
    mapY: 55,
    description: 'Shuttle bus pass issuance, parking permit allocation, and campus transit schedule desk.',
    hourlyTrends: [
      { time: '08:00 AM', count: 25, wait: 7 },
      { time: '10:00 AM', count: 18, wait: 5 },
      { time: '12:00 PM', count: 20, wait: 6 },
      { time: '01:30 PM', count: 12, wait: 3 },
      { time: '03:00 PM', count: 15, wait: 4 },
      { time: '05:00 PM', count: 28, wait: 8 },
    ],
    weeklyTrends: [
      { day: 'Mon', avgWait: 8, peakPeople: 35 },
      { day: 'Tue', avgWait: 5, peakPeople: 28 },
      { day: 'Wed', avgWait: 4, peakPeople: 25 },
      { day: 'Thu', avgWait: 4, peakPeople: 24 },
      { day: 'Fri', avgWait: 7, peakPeople: 32 },
    ],
  },
];

export const INITIAL_CAMERAS: CameraFeed[] = [
  {
    id: 'cam-01',
    code: 'CAM-01',
    locationId: 'canteen',
    locationName: 'Canteen Entrance',
    status: 'LIVE',
    fps: 4.8,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 42,
    modelConfidence: 0.94,
    processingLatencyMs: 42,
  },
  {
    id: 'cam-02',
    code: 'CAM-02',
    locationId: 'library',
    locationName: 'Library Helpdesk',
    status: 'LIVE',
    fps: 5.0,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 18,
    modelConfidence: 0.96,
    processingLatencyMs: 38,
  },
  {
    id: 'cam-03',
    code: 'CAM-03',
    locationId: 'admin-office',
    locationName: 'Admin Clearance Desk',
    status: 'LIVE',
    fps: 4.2,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 67,
    modelConfidence: 0.91,
    processingLatencyMs: 55,
  },
  {
    id: 'cam-04',
    code: 'CAM-04',
    locationId: 'student-services',
    locationName: 'Student Services Foyer',
    status: 'UNSTABLE',
    fps: 2.1,
    queueRegionActive: true,
    resolution: '1280x720 @ 15fps',
    detectedPeopleCount: 34,
    modelConfidence: 0.88,
    processingLatencyMs: 110,
  },
  {
    id: 'cam-05',
    code: 'CAM-05',
    locationId: 'transport-office',
    locationName: 'Transport Permit Window',
    status: 'LIVE',
    fps: 5.0,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 12,
    modelConfidence: 0.95,
    processingLatencyMs: 34,
  },
  {
    id: 'cam-06',
    code: 'CAM-06',
    locationId: 'fee-counter',
    locationName: 'Fee Disbursement Hall',
    status: 'LIVE',
    fps: 4.6,
    queueRegionActive: true,
    resolution: '1920x1080 @ 30fps',
    detectedPeopleCount: 14,
    modelConfidence: 0.93,
    processingLatencyMs: 40,
  },
];

export const INITIAL_ALERTS: SmartAlert[] = [
  {
    id: 'alert-1',
    severity: 'critical',
    type: 'CONGESTION',
    locationId: 'admin-office',
    locationName: 'Administrative Office',
    timestamp: '2 min ago',
    title: 'HIGH CONGESTION DETECTED',
    description: 'Administrative Office queue exceeded 60 people threshold (67 detected). Wait time is 21 min.',
    isRead: false,
  },
  {
    id: 'alert-2',
    severity: 'warning',
    type: 'WAIT_TIME',
    locationId: 'canteen',
    locationName: 'Canteen',
    timestamp: '8 min ago',
    title: 'WAIT TIME INCREASE',
    description: 'Canteen estimated wait time increased to 12 minutes due to lunch rush inflow.',
    isRead: false,
  },
  {
    id: 'alert-3',
    severity: 'success',
    type: 'IMPROVEMENT',
    locationId: 'library',
    locationName: 'Central Library',
    timestamp: '14 min ago',
    title: 'QUEUE IMPROVING',
    description: 'Library queue decreased by 22%. Estimated wait is down to 4 minutes.',
    isRead: true,
  },
  {
    id: 'alert-4',
    severity: 'warning',
    type: 'CAMERA_STATUS',
    locationId: 'student-services',
    locationName: 'Student Services',
    timestamp: '22 min ago',
    title: 'CAMERA STATUS WARNING',
    description: 'Camera CAM-04 connection frame rate dropped to 2.1 FPS. Check network cable or bandwidth.',
    isRead: true,
  },
];

export const DEFAULT_THRESHOLDS: ThresholdSettings = {
  lowMax: 30,
  mediumMax: 60,
  highMin: 61,
  alertSensitivity: 'medium',
  autoStaffNotification: true,
  emailAlertsEnabled: false,
};
